"""Generic verification plans, assertions, and execution engine."""

from invariant_cli.verification.engine import VerificationEngine
from invariant_cli.verification.model import (
    AllOfAssertion,
    AssertionKind,
    EntityAssertion,
    EvidenceFact,
    ExecutableAssertion,
    ExitCodeAssertion,
    ExitCodeOperator,
    FactValue,
    GateResult,
    GateVerdict,
    SetAssertion,
    StateUnchangedAssertion,
    VerificationCandidate,
    VerificationContext,
    VerificationObligation,
    VerificationPlan,
    VerificationReport,
    VerificationScenario,
    VerificationSource,
    VerificationSourceKind,
    VerificationSubject,
)
from invariant_cli.verification.specification import SpecificationGate

__all__ = [
    "AllOfAssertion",
    "AssertionKind",
    "EntityAssertion",
    "EvidenceFact",
    "ExecutableAssertion",
    "ExitCodeAssertion",
    "ExitCodeOperator",
    "FactValue",
    "GateResult",
    "GateVerdict",
    "SetAssertion",
    "StateUnchangedAssertion",
    "VerificationCandidate",
    "VerificationContext",
    "VerificationEngine",
    "VerificationObligation",
    "VerificationPlan",
    "VerificationReport",
    "VerificationScenario",
    "VerificationSource",
    "VerificationSourceKind",
    "VerificationSubject",
    "SpecificationGate",
]
